#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io
# Copyright (c) 2023, HankB
# Copyright (c) 2024 Christopher Bock <christopher@bocki.com>

# Print report header
echo '<<<smart>>>'

for drive in $(sysctl -n kern.disks); do
    # collect SMART results
    report=$(smartctl -a /dev/"${drive}")

    # Extract 2 field Device ID, serial number, manufacturer
    device_id=$(awk '/^(Device Model|Product).*/ {print $NF}' <<< "$report")
    serial=$(awk '/^Serial( |Number).*/ {print $NF}' <<< "$report")

    # build a tag (first field in the output)
    tag=$(tr ' ' '_' <<< "$device_id $serial")

    # full device ID, first three fields in the output
    full_device_id="$tag $device_id"

    # Extract the statistics from the full report
    stats=$(grep -E '^[ 12][ 0-9][0-9]' <<< "$report")
    # TODO Sillly Seagate/Hitachi
    # rep -E 'Vendor:|Product|odel|Serial|Version|Revision|Transport|atabase|Unknown|ogged|eallocated|Spin_Retry|Read_Error|Celsius|Temperature|read:|write:|verify:| [12345]  Short| [12345]  Background'

    # Print out the stats, inserting the full device ID at the start of each line
    # ref: https://unix.stackexchange.com/questions/9784/how-can-i-read-line-by-line-from-a-variable-in-bash
    while IFS= read -r line; do
        echo "$full_device_id $line"
    done < <(printf '%s\n' "$stats")
done
# vim:ft=sh ts=4 sts=4 sw=4 et
